name: GitGuardian Scan

on:
  push:
  pull_request:

jobs:
  gitguardian:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3

    - name: Run GitGuardian scan
      uses: GitGuardian/ggshield-action@v1
      with:
        args: secret scan repo .
